_BASE_: "Base-OVD-RCNN-C4.yaml"
MODEL:
  META_ARCHITECTURE: "CustomRCNNMViT"
  WEIGHTS: saved_models/coco_ovd_base.pth
  PIS_PROP_PATH: datasets/MAVL_proposals/coco_props/class_specific
  ROI_BOX_HEAD:
    WEIGHT_TRANSFER: False
    WS_NUM_PROPS: 32
    IMAGE_LABEL_LOSS: 'pseudo_max_score'
SOLVER:
  BASE_LR: 0.02
  STEPS: (60000, 80000)
  MAX_ITER: 90000
DATASETS:
  TRAIN: ("coco_zeroshot_train_oriorder", "coco_caption_train_tags")
INPUT:
  CUSTOM_AUG: ResizeShortestEdge
  MIN_SIZE_TRAIN_SAMPLING: range
  MIN_SIZE_TRAIN: (800, 800)
DATALOADER:
  SAMPLER_TRAIN: "MultiDatasetSampler"
  DATASET_RATIO: [1, 4]
  USE_DIFF_BS_SIZE: True
  DATASET_BS: [2, 8] # Batch-size per GPU
  USE_RFS: [False, False]
  DATASET_MIN_SIZES: [[800, 800], [400, 400]]
  DATASET_MAX_SIZES: [1333, 667]
  FILTER_EMPTY_ANNOTATIONS: False
  MULTI_DATASET_GROUPING: True
  DATASET_ANN: ['box', 'image']
  NUM_WORKERS: 8
WITH_IMAGE_LABELS: True
OUTPUT_DIR: output/coco_ovd_PIS