_BASE_: "COCO_OVD_Base_PIS.yaml"
MODEL:
  WEIGHTS: saved_models/coco_ovd_rkd.pth
  RKD_FEAT_PATH: datasets/MAVL_proposals/coco_props/classagnostic_distilfeats
  PIS_PROP_PATH: datasets/MAVL_proposals/coco_props/class_specific
  DISTILLATION: True
  DISTIL_L1_LOSS_WEIGHT: 0.15
  NUM_DISTIL_PROP: 5
  IRM_LOSS_WEIGHT: 0.15
  ROI_BOX_HEAD:
    WEIGHT_TRANSFER: True
OUTPUT_DIR: output/coco_ovd_RKD_PIS_WT
TEST:
  EVAL_PERIOD: 10000