_BASE_: "COCO_OVD_RKD_PIS_WeightTransfer.yaml"
OUTPUT_DIR: "output/coco_ral"
SEED: 42516326
USE_RAL: True
RAL_PATH: "ralf/neg_feature_coco.pkl"
RAL_RAND_N: 10
WITH_TRIPLET_HN: True
WITH_TRIPLET_EN: True
MARGIN_HN: 0.0
MARGIN_EN: 1.0
LAMBDA_HN: 1.0
LAMBDA_EN: 10.0
STRENGTH_HN: 1.0
STRENGTH_EN: 1.0
DATALOADER:
  DATASET_BS: [4, 16]