_BASE_: "mask_rcnn_R50FPN_CLIP_sigmoid.yaml"
MODEL:
  WEIGHTS: saved_models/lvis_ovd_base.pth
  RKD_FEAT_PATH: datasets/MAVL_proposals/coco_props/classagnostic_distilfeats
  DISTILLATION: True
  DISTIL_L1_LOSS_WEIGHT: 0.25
  NUM_DISTIL_PROP: 5
  IRM_LOSS_WEIGHT: 0.13
OUTPUT_DIR: output/lvis_ovd_RKD