_BASE_: "LVIS_OVD_Base_PIS.yaml"
MODEL:
  WEIGHTS: saved_models/lvis_ovd_rkd.pth
  RKD_FEAT_PATH: datasets/MAVL_proposals/lvis_props/classagnostic_distilfeats/coco_distil_feats
  RKD_ILS_FEAT_PATH: datasets/MAVL_proposals/lvis_props/classagnostic_distilfeats/imagenet_distil_feats
  PIS_PROP_PATH: '' # datasets/MAVL_proposals/lvis_props/class_specific/imagenet_lvis_props (if pseudo props must be loaded from files)
  DISTILLATION: True
  DISTIL_L1_LOSS_WEIGHT: 0.25
  NUM_DISTIL_PROP: 5
  IRM_LOSS_WEIGHT: 0.13
  ROI_BOX_HEAD:
    WEIGHT_TRANSFER: True
SEED: 9112072
OUTPUT_DIR: output/lvis_ovd_RKD_PIS_WT
TEST:
  EVAL_PERIOD: 0