_BASE_: "LVIS_OVD_RKD_PIS_WeightTransfer.yaml"
OUTPUT_DIR: "output/lvis_ral"
SEED: 9112072
USE_RAL: True
RAL_PATH: "ralf/neg_feature_lvis.pkl"
RAL_RAND_N: 10
WITH_TRIPLET_HN: True
WITH_TRIPLET_EN: True
MARGIN_HN: 0.0
MARGIN_EN: 1.0
LAMBDA_HN: 1.0
LAMBDA_EN: 5.0
STRENGTH_HN: 1.0
STRENGTH_EN: 1.0
DATALOADER:
  DATASET_BS: [4, 16]